ALTER TABLE "tenants"
ADD COLUMN "payrollBasicRate" DECIMAL(5,2) NOT NULL DEFAULT 65,
ADD COLUMN "payrollHousingRate" DECIMAL(5,2) NOT NULL DEFAULT 25,
ADD COLUMN "payrollTransportRate" DECIMAL(5,2) NOT NULL DEFAULT 10;
