ALTER TABLE "job_titles"
ADD COLUMN "maxGrade" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN "gradeIncrement" DECIMAL(10,2) NOT NULL DEFAULT 0,
ADD COLUMN "housingAllowance" DECIMAL(10,2) NOT NULL DEFAULT 0,
ADD COLUMN "transportAllowance" DECIMAL(10,2) NOT NULL DEFAULT 0,
ADD COLUMN "otherAllowance" DECIMAL(10,2) NOT NULL DEFAULT 0,
ADD COLUMN "insuranceRate" DECIMAL(5,2) NOT NULL DEFAULT 0,
ADD COLUMN "customAllowances" JSONB NOT NULL DEFAULT '[]';

ALTER TABLE "employees"
ADD COLUMN "jobGrade" INTEGER;
